### ISSUE TITLE
TODO: code documentation

### ISSUE THREAD

**Issue by YiiRocks** [YiiRocks/yii2-fontawesome-inline#1]
## Deal breaking bugs
[PHP-Files/Classes are missing](https://github.com/yiisoft/yii2-apidoc/issues/162) - severely impacting the value of the documentation export
[Incorrect output when typehinting a variable as string](https://github.com/yiisoft/yii2-apidoc/issues/179) - makes output confusing

## Would be nice at a later stage
[Add support for `@method` tags](https://github.com/yiisoft/yii2-apidoc/issues/136)

Documentation itself is mostly done.
`docs/*` will be deleted, once an export (either md-files or HTML (preferred)) can be exported without issues.

See https://fai.mr42.me/ for current status.

**Comment by Thoulah** [comment]
Stuck with the current docs for now, as https://github.com/yiisoft/yii2-apidoc/issues/162 have been encountered here as well.

**Comment by Thoulah** [comment]
Documentation itself is mostly done.
`docs/*` will be deleted, once an export (either md-files or HTML (preferred)) can be exported without issues.

**Comment by Mister-42** [comment]
Documention is on https://www.yii.rocks/yii2-fontawesome-inline/
